services:
  db:
    image: postgres:14.1-alpine
    restart: no
    environment:
      - POSTGRES_USER=librarian
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
